const RESULTS = {
    OK: 0,
    ERROR: 1,
    TOKENINVALID: 2,
    TOKENEXPIRED: 3,
    NOTOKEN: 4,
    CHANGEPASSWORD: 5,
    PASSWORDINVALID: 6,
    USERINVALID: 7,
    JSONINVALID: 8,
    NOEMAIL: 9,
    INVALIDCODE: 10,
    REPITED: 11,
    NOAFECTED: 12,
    SESIONANOTHER: 13,
    INVALIDIP: 14
};
module.exports = RESULTS;